namespace Symbiote.OperationResult
{
    /// <summary>
    /// Represents messages generated by operations.
    /// </summary>
    public class Message
    {
        #region Properties

        /// <summary>
        /// The type of the message.
        /// </summary>
        public MessageType Type { get; set; }

        /// <summary>
        /// The content of the message.
        /// </summary>
        public string Text { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// Constructs a message of the optionally supplied type with the optionally supplied message.
        /// </summary>
        /// <param name="type">The type of the message.</param>
        /// <param name="text">The content of the message.</param>
        public Message(MessageType type = MessageType.Info, string text = "")
        {
            Type = type;
            Text = text;
        }

        #endregion

        #region Instance Methods

        /// <summary>
        /// Returns a formatted string representation of the message.
        /// </summary>
        /// <returns>The formatted message string.</returns>
        public override string ToString()
        {
            return "[" + Type.ToString().ToUpper() + "] " + Text;
        }

        #endregion
    }
}
